name: "Flutter App -> Build(Android & IOS), Test(Firebase TestLab) & Release"
on:
  push:
    branches:
      - master
jobs:
  build-android:
    name: Build & upload aab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'
      # - name: Increment Build number
      #   run: perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.(${{github.run_number}})/e' pubspec.yaml
      - name: Get Flutter Pub
        run: flutter pub get
      # - run: flutter test 
      # - name: Decoding android/key.properties
      #   run: echo "${{ secrets.KEYPROP_PROD }}" | base64 --decode > android/key.properties
      # - name: Decoding android/neumodore_key.jks
      #   run: echo "${{ secrets.KEYJKS_PROD }}" | base64 --decode > android/app/key.jks
      - run: flutter build appbundle --release --no-sound-null-safety
      - name: upload aab to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app-release-aab
          path: 'build/app/outputs/bundle/release/app-release.aab'
      - name: upload mapping file to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: android-mapping
          path: 'build/app/outputs/mapping/release/mapping.txt'
  build-ios:
    name: IOS Production Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: add java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Restore Pods cache
        uses: actions/cache@v2
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Pods
        run: cd ios && pod install --repo-update && cd ..
      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: ./ios/Runner.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: "iPhone Distribution"
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ./ios/Runner.xcworkspace
          scheme: "Runner"
      - name: upload ipa
        uses: actions/upload-artifact@v1
        with:
          name: ipa-production-release
          path: output.ipa
  # testlab:
  #   name: Firebase Test Lab
  #   needs: build-android
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         ref: production
  #     - name: Download app bundle
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: app-production-release
  #     - name: 'Auth Google CLI'
  #       uses: 'google-github-actions/auth@v0'
  #       with:
  #         credentials_json: '${{ secrets.GCP_FIREBASE_CREDENTIALS }}'

  #     - name: 'Set up Cloud SDK'
  #       uses: 'google-github-actions/setup-gcloud@v0'

  #     - name: List Available devices
  #       run: gcloud firebase test android models list

  #     - name: Run Robo Tests in Firebase Test Lab
  #       run: gcloud firebase test android run --type robo --device model=Pixel3,version=30,locale=en,orientation=portrait --app ./app-production-release/app-production-release.aab --results-dir=${{ github.run_number }}
      
  #     - name: create result directory
  #       run: mkdir ./results

  #     - name: Download video
  #       run: gsutil cp gs://test-lab-bydj68vmsh0c8-w51km6dvhab4q/${{ github.run_number }}/Pixel3-30-en-portrait/video.mp4 ./results

  #     - name: Download Screenshots
  #       run: gsutil -m cp -r gs://test-lab-bydj68vmsh0c8-w51km6dvhab4q/${{ github.run_number }}/Pixel3-30-en-portrait/artifacts/ ./results

  #     - name: upload video to artifacts 
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: Video
  #         path: ./results/video.mp4

  #     - name: upload Screenshots to artifacts 
  #       uses: actions/upload-artifact@v1
  #       with:
  #         name: Screenshots
  #         path: ./results/artifacts/
  upload_testflight:
    name: TestFlight upload
    needs: build-ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Download ipa
        uses: actions/download-artifact@v1
        with:
          name: ipa-production-release
      - name: Upload app to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: './ipa-production-release/output.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
  release:
    name: release
    needs: [upload_testflight]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Download app bundle
        uses: actions/download-artifact@v1
        with:
          name: app-production-release
      # - name: Download video
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: Video
      # - name: Download screenshots
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: Screenshots
      # - name: Zip Screenshots
      #   run: zip -r Screenshots Screenshots
      - name: Download ipa
        uses: actions/download-artifact@v1
        with:
          name: ipa-production-release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./app-production-release/app-production-release.aab, ./ipa-production-release/output.ipa"
          tag: v0.0.1 - ${{ github.run_number }} #TODO(skandar) pick version number from pubspec.yml
          token: ${{ secrets.GITHUB_TOKEN }}
  sendNotification:
        name: Send Notification
        needs: release
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Echo Notification
          run: echo "Notificaton sent !"