name: "Flutter App -> Build(Android & IOS), Test(Firebase TestLab) & Release"
on:
  push:
  release:
    types: [published]
jobs:
  build-android:
    name: Build & upload aab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: print flutter version
        run: echo ${${env.version}:1:1}
        env:
          version: flutter --version

      - name: print git hash
        run:  echo $(git log -n1 --date=short --format="%h")
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'
      # - name: Increment Build number
      #   run: perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.(${{github.run_number}})/e' pubspec.yaml
      - name: Get Flutter Pub
        run: flutter pub get
      # - run: flutter test
      # - name: Decoding android/key.properties
      #   run: echo "${{ secrets.KEYPROP_PROD }}" | base64 --decode > android/key.properties
      # - name: Decoding android/neumodore_key.jks
      #   run: echo "${{ secrets.KEYJKS_PROD }}" | base64 --decode > android/app/key.jks
      - name: Build app bundle
        run: flutter build appbundle --release $ARGS
        env:
          GIT_COMMIT_DATE: $(git log -n1 --date=short --format="%ad")
          GIT_COMMIT_HASH: $(git log -n1 --date=short --format="%h")
          FLUTTER_VERSION: ${$(flutter --version):8:6}
          ARGS: "--dart-define=TRACKR_GIT_COMMIT_DATE=$GIT_COMMIT_DATE --dart-define=TRACKR_GIT_COMMIT_HASH=$GIT_COMMIT_HASH --dart-define=TRACKR_FLUTTER_VERSION=${FLUTTER_VERSION}"
      - name: upload aab to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app-production-release
          path: 'build/app/outputs/bundle/release/app-release.aab'
      - name: upload mapping file to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: android-mapping
          path: 'build/app/outputs/mapping/release/mapping.txt'
