name: "Flutter App -> Build(Android & IOS), Test(Firebase TestLab) & Release"
on:
  push:
  release:
    types: [published]
jobs:
  build-android:
    name: Build & upload aab
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: print git hash
        run:  echo $(git log -n1 --date=short --format="%h")
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.0'
          channel: 'stable'
      - name: Get Flutter version
        run: echo "::set-output name=FLUTTER_VERSION::$(flutter --version)"
        id: version
      - name: print flutter version
        run : echo "${{ steps.version.outputs.FLUTTER_VERSION }}:1:1"
      # - name: Increment Build number
      #   run: perl -i -pe 's/^(version:\s+\d+\.\d+\.\d+\+)(\d+)$/$1.(${{github.run_number}})/e' pubspec.yaml
      - name: Get Flutter Pub
        run: flutter pub get
      # - run: flutter test
      # - name: Decoding android/key.properties
      #   run: echo "${{ secrets.KEYPROP_PROD }}" | base64 --decode > android/key.properties
      # - name: Decoding android/neumodore_key.jks
      #   run: echo "${{ secrets.KEYJKS_PROD }}" | base64 --decode > android/app/key.jks
      - name: Build apk
        run: |
          set -- ${{ steps.version.outputs.FLUTTER_VERSION }}
          flutter build apk --release --dart-define=TRACKR_GIT_COMMIT_DATE=$(git log -n1 --date=short --format="%ad") --dart-define=TRACKR_GIT_COMMIT_HASH=$(git log -n1 --date=short --format="%h") --dart-define=TRACKR_FLUTTER_VERSION="$2"

      - name: upload aab to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app-production-release
          path: 'build/app/outputs/apk/release/app-release.apk'
      - name: upload mapping file to artifacts
        uses: actions/upload-artifact@v1
        with:
          name: android-mapping
          path: 'build/app/outputs/mapping/release/mapping.txt'
